### PR TITLE
Add libnx port

### PR DESCRIPTION
**Pull request by slash0042**
This is a port of Mesen-libretro for Nintendo Switch. Performance is quite good if you overclock to 1700 Mhz, but with hdpacks performance isn't that great (50-45fps, dunno if something can be done on that reward). OGG support is broken for some reason (it crashes the emu by some recursive func) and I have some warnings when building stb_vorbis:
`../Utilities/stb_vorbis.cpp: In function 'int stb_vorbis_get_frame_short(stb_vorbis*, int, short int**, int)':
../Utilities/stb_vorbis.cpp:4798:28: warning: 'output' may be used uninitialized in this function [-Wmaybe-uninitialized]
 4798 |       convert_samples_short(num_c, buffer, 0, f->channels, output, 0, len);
      |       ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Utilities/stb_vorbis.cpp: In function 'int stb_vorbis_get_frame_short_interleaved(stb_vorbis*, int, short int*, int)':
../Utilities/stb_vorbis.cpp:4724:35: warning: 'output' may be used uninitialized in this function [-Wmaybe-uninitialized]
 4724 |                buffer[i] += data[j][d_offset+o+i];
      |                             ~~~~~~^
../Utilities/stb_vorbis.cpp:4794:12: note: 'output' was declared here
 4794 |    float **output;
      |            ^~~~~~
../Utilities/stb_vorbis.cpp: In function 'int stb_vorbis_decode_filename(const char*, int*, int*, short int**)':
../Utilities/stb_vorbis.cpp:4786:49: warning: 'output' may be used uninitialized in this function [-Wmaybe-uninitialized]
 4786 |          copy_samples(buffer[i]+b_offset, data[i]+d_offset, samples);
      |                                           ~~~~~~^
../Utilities/stb_vorbis.cpp:4794:12: note: 'output' was declared here
 4794 |    float **output;
      |            ^~~~~~
../Utilities/stb_vorbis.cpp: In function 'int stb_vorbis_decode_memory(const uint8*, int, int*, int*, short int**)':
../Utilities/stb_vorbis.cpp:4786:49: warning: 'output' may be used uninitialized in this function [-Wmaybe-uninitialized]
 4786 |          copy_samples(buffer[i]+b_offset, data[i]+d_offset, samples);
      |                                           ~~~~~~^
../Utilities/stb_vorbis.cpp:4794:12: note: 'output' was declared here
 4794 |    float **output;
      |            ^~~~~~`

I'm open for suggestions.

`

### CODE REVIEW

**Comment by SourMesen** [comment]
For the PI constant, you can just remove the math header & the _USE_MATH_DEFINES define and keep the M_PI define for all builds - I'm pretty sure this is what I ended up doing in Mesen-S' code but forgot to change it here, apparently.

I'm not sure what could be wrong with stb_vorbis, unfortunately.  Is the Switch little endian?

As for HD Packs, they could probably be made to be faster - technically they can run in a separate thread which improves performance by a fair amount, but the libretro API makes this somewhat hard to pull off without introducing an extra frame of input lag, I think, unfortunately. (which is why it's single threaded at the moment for libretro)

**Comment by slash0042** [comment]
@SourMesen it is little endian, already fixed all my defines so it may fix OGG support, will test once I'm at home

**Comment by slash0042** [comment]
So OGG still  crashes the emu, I'm out of ideas at this point, the only thing I can guess is I'm missing some define from stb_vorbis.

**Comment by SourMesen** [comment]
Thanks - let's merge it as-is for now, at least everything other than HD packs should work.

Re: multithreading, the way it works is that the conversion of a regular frame to a HD frame runs in another thread, but not while the frame is being emulated. Once the frame is done, another thread can generate the HD version, while the emulation core starts running the next frame.  The only way I can see to do this with the libretro API would be to start the next frame's rendering 1 frame ahead of time, so it would add an extra frame of input lag (so it would need to be an option, etc.)  I won't have the time to look into changing this soon, though, most likely.

**Pull request merged**
